### ISSUE TITLE
Traversing child nodes, except of nodes being descendants of specific node types

### ISSUE THREAD

**Issue by pako-pl** [grom358/pharborist#186]
When doing static code analisys, context of a currenly processed call is very important. Right now there is no easy way to "skip" some nodes that shouldn't be matched by find() based on the type of their parent.

````
public function example() {
  $x = 1;
  $fun = function() use($x) {
    if($x == 1) {
       $z = 2;
    }
  }
}
````

Let's say I would like to find all assignments inside the example() method, except for assignments contained inside the anonymous function, which belong to a different scope. I can use find() with an isInstanceOf() filter on the example() method node, but it will also match the assignments from the anonynous function. Any suggestions as to filter those out in an efficient way? Or perhaps there should be some more specialized filter for this use case?

**Comment by grom358** [comment]
Added the callback returning FALSE to not walk down that parent node.
