### ISSUE TITLE
We need InterfaceNode::getMethods()

### ISSUE THREAD

**Issue by phenaproxima** [grom358/pharborist#222]
There's no way to iterate through the methods defined by an interface! This is pretty essential.

**Comment by phenaproxima** [comment]
I'm willing to take this on but I'm not sure how interfaces are handled by the parser. It looks like they create InterfaceMethodNodes for each method of the interface, but there's also InterfaceStatementNode, whose purpose is unclear.

**Comment by grom358** [comment]
Added to master
