### ISSUE TITLE
Pass the filename from the Parser to the Node

### ISSUE THREAD

**Issue by pfrenssen** [grom358/pharborist#230]
In #228 the ability to retrieve the filename of a Node was restored, but currently the Parser doesn't pass the filename on so all Nodes will have the filename '`source`'.

**Comment by grom358** [comment]
Ah I sound of made a test for this doh!!.. Can you do a pull request so you get the credit?

**Comment by pfrenssen** [comment]
@grom358, sure I already did, it's here: #231.

**Comment by pfrenssen** [comment]
Thanks!
